# get_best_params.py
"""
Using the DataFrame generated by add_hyperparam_data.py, find the parameters
that attained the best loss value for each test type. Note that the script
bases comparisons on the "filename" parameter.
"""

import pandas as pd
import numpy as np

# Read the data
csv_name = "best_hyperparams.csv"
data = pd.read_csv("hyperparameter_data.csv")

types = data.groupby("filename")        # Group the data
best_ind = []
for group in list(types.groups):
    # Get the indices of the trials with the best loss values
    index = types.get_group(group)["best_loss"].idxmin()
    if np.isnan(index):
        print("Failed:", index)
        
    best_ind.append(types.get_group(group)["best_loss"].idxmin())
    
# Convert to .csv that can be read by the Analyzer class
data.loc[best_ind].to_csv(csv_name, index=False)
